# Generated by Django 4.0.4 on 2022-05-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_empowerfaqs_empoweringpagefaqs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empoweringpage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='refugespage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='skillspage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='talentpage',
            name='hero_image',
        ),
    ]
