# Generated by Django 4.0.4 on 2022-05-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_empoweringpage_hero_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empoweringpage',
            name='icon_class_1',
        ),
        migrations.RemoveField(
            model_name='empoweringpage',
            name='icon_class_2',
        ),
        migrations.RemoveField(
            model_name='empoweringpage',
            name='icon_class_3',
        ),
        migrations.RemoveField(
            model_name='empoweringpage',
            name='icon_class_4',
        ),
        migrations.RemoveField(
            model_name='refugespage',
            name='icon_class_1',
        ),
        migrations.RemoveField(
            model_name='refugespage',
            name='icon_class_2',
        ),
        migrations.RemoveField(
            model_name='refugespage',
            name='icon_class_3',
        ),
        migrations.RemoveField(
            model_name='refugespage',
            name='icon_class_4',
        ),
        migrations.RemoveField(
            model_name='skillspage',
            name='icon_class_1',
        ),
        migrations.RemoveField(
            model_name='skillspage',
            name='icon_class_2',
        ),
        migrations.RemoveField(
            model_name='skillspage',
            name='icon_class_3',
        ),
        migrations.RemoveField(
            model_name='skillspage',
            name='icon_class_4',
        ),
        migrations.RemoveField(
            model_name='talentpage',
            name='icon_class_1',
        ),
        migrations.RemoveField(
            model_name='talentpage',
            name='icon_class_2',
        ),
        migrations.RemoveField(
            model_name='talentpage',
            name='icon_class_3',
        ),
        migrations.RemoveField(
            model_name='talentpage',
            name='icon_class_4',
        ),
    ]
